### ISSUE TITLE
Creating Home page

### ISSUE THREAD

**Issue by JomanaMohamed01** [JomanaAhmed01/ai-company-website#1]

**Comment by JomanaAhmed01** [comment]
* Creating Navbar section
* Creating Header section
* Creating Vision section
* Creating Services section
* Creating Autonomous driving section
* Creating Real-Time info section
* Creating Perception enabled section
* Creating Why autono section
* Creating Autono in numbers section
* Creating Industry section
* Creating Careers section
* Creating Footer section
